services:
  - type: web
    name: viegas-lima-site
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "bash start.sh"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "viegaselima.com.br,www.viegaselima.com.br,viegas-lima-site.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://viegaselima.com.br,https://www.viegaselima.com.br,https://viegas-lima-site.onrender.com"
      - key: SITE_URL
        value: "https://viegaselima.com.br"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PG_HOST
        value: "dpg-d994vr77f7vs739qfnv0-a"
      - key: PG_PORT
        value: "5432"
      - key: PG_USER
        value: "gagbot"
      - key: PG_PASSWORD
        value: "Rsf1ILd3T7NH7FLoPoZM4xJiNAXTvsSF"
    healthCheckPath: /contato/
    autoDeploy: true
