# Generated by Django 5.1.4 on 2026-08-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('cliente_ficticio', models.CharField(help_text='Nome fictício pra ilustrar', max_length=120)),
                ('setor', models.CharField(choices=[('industria', 'Indústria'), ('servicos', 'Serviços'), ('comercio', 'Comércio'), ('tecnologia', 'Tecnologia'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('agro', 'Agronegócio'), ('construcao', 'Construção'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('resumo', models.TextField(help_text='Resumo do desafio + resultado em 1 parágrafo')),
                ('problema', models.TextField(help_text='Qual era o problema/dor do cliente')),
                ('solucao', models.TextField(help_text='O que fizemos')),
                ('resultado', models.TextField(help_text='Resultado obtido (incluir números se possível)')),
                ('resultado_numero', models.CharField(blank=True, help_text="Ex: 'R$ 2,5M economizados'", max_length=50)),
                ('duracao', models.CharField(blank=True, help_text="Ex: '8 meses'", max_length=80)),
                ('publicado', models.BooleanField(default=False)),
                ('destaque', models.BooleanField(default=False, help_text='Aparece na home?')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Case de Estudo',
                'verbose_name_plural': 'Cases de Estudo',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
