# Generated by Django 5.1.4 on 2026-08-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('titulo', models.CharField(max_length=180)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('descricao_curta', models.CharField(help_text='Usada em cards e meta description', max_length=255)),
                ('conteudo', models.TextField(help_text='HTML ou Markdown')),
                ('icone', models.CharField(default='⚖️', max_length=4)),
                ('cor_destaque', models.CharField(default='#B8860B', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('destaque_home', models.BooleanField(default=False, help_text='Mostrar na home?')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Página Tributário',
                'verbose_name_plural': 'Páginas Tributário',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
