# Generated by Django 5.1.4 on 2026-08-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cargo_empresa', models.CharField(blank=True, max_length=180)),
                ('texto', models.TextField()),
                ('estrelas', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Numerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text="Ex: '150+', 'R$ 50M', '15'", max_length=20)),
                ('rotulo', models.CharField(help_text="Ex: 'Casos resolvidos'", max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('icone', models.CharField(default='⚖️', help_text='Emoji opcional', max_length=4)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Indicador Numérico',
                'verbose_name_plural': 'Indicadores Numéricos',
                'ordering': ['ordem', 'valor'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, default='(61) 99999-9999', max_length=20)),
                ('whatsapp', models.CharField(blank=True, default='5561999999999', max_length=20)),
                ('email', models.EmailField(default='contato@viegaselima.com.br', max_length=254)),
                ('endereco', models.CharField(blank=True, default='Ceilândia-DF', max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('oab', models.CharField(default='OAB/DF 36.362', max_length=50)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('whatsapp_mensagem', models.CharField(default='Olá, gostaria de uma consulta sobre direito tributário.', max_length=255)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='sites.site')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
