# Generated by Django 5.1.4 on 2026-08-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=180)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('area', models.CharField(choices=[('tributario', 'Direito Tributário'), ('empresarial', 'Direito Empresarial / M&A'), ('civil', 'Direito Cível'), ('trabalhista', 'Direito Trabalhista'), ('previdenciario', 'Direito Previdenciário'), ('familia', 'Direito de Família'), ('outro', 'Outro')], default='tributario', max_length=30)),
                ('mensagem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
