# Generated by Django 5.1.4 on 2026-08-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao_curta', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('icone', models.CharField(default='🏢', max_length=4)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Página Empresarial',
                'verbose_name_plural': 'Páginas Empresariais',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
